### ISSUE TITLE
0xwho Image asset

### ISSUE THREAD

**Issue by lxhyl** [lxhyl/0xwho#1]
<img width="635" alt="image" src="https://github.com/lxhyl/0xwho/assets/41041503/0a4f8668-0182-4686-a04a-48760c7e6b08">

**Comment by lxhyl** [comment]
<img width="1314" alt="Screenshot 2023-08-27 at 00 18 40" src="https://github.com/lxhyl/0xwho/assets/41041503/f2444f96-7544-4741-80fc-fbea45395ccd">
<img width="1246" alt="Screenshot 2023-08-27 at 00 17 57" src="https://github.com/lxhyl/0xwho/assets/41041503/6e20450e-0b06-43b8-bf62-34e11878fe03">

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
bmark88, @DIMCHERRY, @sumonst21, @0xdevant, @JAIIIEZ, @JacZhoulang, @amadeobrands, @ngas-wakefield, @jinbangyi, @Domsab, @YunChe404, @reihanehamini, @vittorisantiago, @gonzalolater, @Th1983, @GDdark, @yes00101, @agustiza, @jacksondoherty, @BlackLotusAL, @konnyaku256, @xieweizhi, @ALADAG-Seyit-Mehmet, @CaoManhDat, @JacekDuszenko, @GitMac32, @ryandkyle, @omartaha15, @aminazadian, @AneeshSachdeva, @hzmhuhu, @steven-tomlinson, @JimCat1103, @toprakkeskin, @cryptokeenz, @jaspeen, @ErickRosado, @knikos, @RuniYunk, @anproghub, @Xavier-Cliquennois, @soaple, @moodycoins, @its-hero, @YashKarthik, @leandroglopez, @younianhuang, @lukaszwazny, @Nyaksik, @EntraptaJjagadeshkoba, @alex-bormotov, @XuHaoIgeneral, @chuangbo, @realChenHui, @mohammadnaraghi, @flamuri-dev, @Xavier-Cliquennois, @kaarliceek, @abgnpr, @peterszombati, @Ektamd02, @inventionsbyhamid, @adilkhali, @MHarris021, @dongzoolee, @time1010820, @samyeh621109, @Hpbbs, @blackqueentech, @geek4ctrl, @0xRajkumar, @yumirkov, @FatTigerWang, @CryptoGod69420, @donniedarkpool, @paulyc, @kevinxiong, @d4mk0, @fandf, @nslogx, @TenaciousJai, @brbenji, @zouantchaw, @moust, @yusufferdogan, @EuJinnLucaShow, @kingdom998, @steven-varga, @prxgr4mm3r, @Ghostsarah0042, @negin-1, @tumobi, @m4n3z40, @E-Zbox, @sepiroth-x, @MohammedAlhalwachi, @longyangxi, @AlbericoD, @mwogates
